# This is a basic workflow to help you get started with Actions
name: Use pre and post

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Main:
    name: The only job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Get sources
      - name: Just an echo
        run: echo "the step after checkout"
      - uses: ActionsWorkshopOrg/CustomActions/.github/actions/pre-and-post@main
        name: Run the custom action
        with:
          premessage: Let's start!
          message: We are just in the midle
          postmessage: Finishing!
      - uses: ./.github/actions/pre-and-post
        name: Run the custom action locally (without pre)
        with:
          premessage: Let's start!
          message: We are just in the midle
          postmessage: Finishing!
      
      - name: Annotations
        run: |
          echo ::notice title=Simple annotation::Hello world!.
          echo ::notice title=Repository Link::This is the repository url: ${{ github.server_url }}/${{ github.repository }}. Reported by run ${{ github.run_id }}.
  
      
      
